# Generated by Django 3.0.2 on 2020-02-12 16:08

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("main", "0004_auto_20200212_1906"),
    ]

    operations = [
        migrations.AddField(
            model_name="tutorial",
            name="tutorial_series",
            field=models.ForeignKey(
                default=1,
                on_delete=django.db.models.deletion.SET_DEFAULT,
                to="main.TutorialSeries",
                verbose_name="Series",
            ),
        ),
        migrations.AddField(
            model_name="tutorial",
            name="tutorial_slug",
            field=models.CharField(default=1, max_length=200),
        ),
    ]
