# Generated by Django 3.0.2 on 2020-02-12 16:04

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("main", "0002_tutorialcategory_tutorialseries"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="tutorialseries",
            options={"verbose_name_plural": "Series"},
        ),
        migrations.AddField(
            model_name="tutorial",
            name="tutorial_series",
            field=models.ForeignKey(
                default=1,
                on_delete=django.db.models.deletion.SET_DEFAULT,
                to="main.TutorialSeries",
                verbose_name="Series",
            ),
        ),
        migrations.AddField(
            model_name="tutorial",
            name="tutorial_slug",
            field=models.CharField(default=1, max_length=200),
        ),
        migrations.AddField(
            model_name="tutorialseries",
            name="series_summary",
            field=models.CharField(default=0, max_length=200),
        ),
        migrations.AddField(
            model_name="tutorialseries",
            name="tutorial_category",
            field=models.ForeignKey(
                default=1,
                on_delete=django.db.models.deletion.SET_DEFAULT,
                to="main.TutorialCategory",
                verbose_name="Category",
            ),
        ),
        migrations.AddField(
            model_name="tutorialseries",
            name="tutorial_series",
            field=models.CharField(default=0, max_length=200),
        ),
    ]
