# Generated by Django 3.0.2 on 2020-02-12 15:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("main1", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="TutorialCategory",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "tutorial_category",
                    models.CharField(max_length=200),
                ),
                (
                    "category_summary",
                    models.CharField(max_length=200),
                ),
                (
                    "category_slug",
                    models.CharField(default=1, max_length=200),
                ),
            ],
            options={"verbose_name_plural": "Categories",},
        ),
        migrations.CreateModel(
            name="TutorialSeries",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
            ],
        ),
    ]
