# Generated by Django 3.0.2 on 2020-02-19 16:13

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main1', '0007_auto_20200212_1949'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tutorial',
            name='tutorial_published',
            field=models.DateTimeField(default=datetime.datetime.now, verbose_name='date published'),
        ),
        migrations.AlterField(
            model_name='tutorial',
            name='tutorial_slug',
            field=models.CharField(max_length=200),
        ),
        migrations.AlterField(
            model_name='tutorialcategory',
            name='category_slug',
            field=models.CharField(max_length=200),
        ),
        migrations.AlterField(
            model_name='tutorialseries',
            name='series_summary',
            field=models.CharField(max_length=200),
        ),
        migrations.AlterField(
            model_name='tutorialseries',
            name='tutorial_series',
            field=models.CharField(max_length=200),
        ),
    ]
